[package]
name = "lattice-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
lattice-types = { path = "../lattice-types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
