[package]
name = "lattice-macros-test"
version = "0.1.0"
edition = "2024"

[dependencies]
lattice-macros = { path = "../lattice-macros" }
lattice-types = { path = "../lattice-types" }
once_cell = "1.19.0"
