[package]
name = "resonance_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
resonance_core = { path = "../resonance_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
syn = { version = "2.0", features = ["full"] }
glob = "0.3.1"
toml = "0.8.12"
